version: '3'

services:
    api:
        build: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/usr/src/app
        links:
            - database
    database:
        image: postgres:12
        container_name: rocket_db
        hostname: rocket_db
        ports: 
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: supersecretpassword
            PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
    pgdata: {}
